### ISSUE TITLE
自定义的Model可以打印么

### ISSUE THREAD

**Issue by wtuyp** [DeveloperLx/LxDBAnything#2]
比如有个Model
@interface UserInfo : NSObject
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *age;
@end

UserInfo *user;
Log(user)打印出每个属性的值，可以吗？谢谢！

**Comment by DeveloperLx** [comment]
这个东西超级好做，你去参考下mantle、restkit、jsonModel、mjextenstion之类的开源库，自己都能搞得出来

**Comment by DeveloperLx** [comment]
已添加该功能
