### ISSUE TITLE
新建的工程 ，直接pod或者拖入项目报错。

### ISSUE THREAD

**Issue by yimouleng** [DeveloperLx/LxDBAnything#3]
新建的工程 ，直接pod或者拖入项目报错。 
使用的时候 报C99错误。 
h文件，我肯定不用加入头文件的，  启示我试过加头文件， 会报错。

直接调用 LxDBAnyVar(xx); 会报错。
 Implicit declaration of function 'LxDBAnyVar' is invalid in C99
微博不理我，Q群不理我， 这里再不理我，我就可以放弃了= =

**Comment by yimouleng** [comment]
我试过很多方法，来取消c99错误， 可是都没有成功， 这包括添加#import <objc/runtime.h>，修改C Language Dialect 等

**Comment by yimouleng** [comment]
测试， 用pod导入 使用时会报C99错误，   直接拖拽进工程， 加入头文件不会报错。

**Comment by DeveloperLx** [comment]
https://github.com/DeveloperLx/LxProjectTemplate 就是用的pod集成的本项目，没做过任何特别的设置，没出现过任何问题。你应该从你本地的项目中找问题出现的原因
